### ISSUE TITLE
Cant Open The Exe File

### ISSUE THREAD

**Issue by idontrule** [Steviegt6/ruler#1]
So whenever I try to open the .exe file,it says this:

! Can't run "C:\Users\pc0\AppData\Local\Temp\Rar$EXa5032.16713\Ruler.IRule.exe"

I hope you fix this and have a good day.

**Comment by Steviegt6** [comment]
If it can't run, you need .NET 6 installed. You can get it [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). Select the Runtime option.

**Comment by Steviegt6** [comment]
Closed, please create a new issue if you face any other problems.
