### ISSUE TITLE
Unable to open the .exe file

### ISSUE THREAD

**Issue by nkj12** [Steviegt6/ruler#5]
I have downloaded the zip file for the automatic installer but was unable  to find out how to download it. This is on mac, and when I press the .exe file, it just opens up my unzipper. Do I need wine or is there a different download for mac.

**Comment by Steviegt6** [comment]
I.RULE is not supported on Mac.

For the record, Ruler.IRule will totally run on Mac, it'll just fail to launch the game. I'd recommend installing I.RULE withoutr RULER and just using Bootcamp.
